# -*- coding: utf-8 -*-
"""
reporting_pdf_builders.py — PDF builder helpers for expert request reports.

Extracted from shared_request_routes.py (refactor Step 3).
Contains draft PDF, simple valuation PDF, and certified report PDF builders.

No Flask, no route handlers, no auth, no workbook/Excel logic.
"""
from __future__ import annotations

import json
import uuid
from datetime import datetime
from pathlib import Path

from reporting_method_context import _build_method_context  # noqa: F401

# Storage paths — mirrors shared_request_routes.py; both files live in core_engine/
_BASE              = Path(__file__).parent / "instance" / "requests"
_REPORTS           = _BASE / "reports"
_CERTIFIED_REPORTS = Path(__file__).parent / "instance" / "certified_reports"
_TMPL_DIR          = Path(__file__).parent / "templates" / "pdf"

_PDF_TITLES: dict[str, str] = {
    "tax_appeal":             "تقرير فحص ضريبة عقارية مبدئي",
    "simple_valuation":       "تقرير تقييم عقاري مبدئي",
    "chat":                   "ملخص استشارة عقارية مبدئية",
    "professional_valuation": "مسودة مراجعة تقييم احترافي",
    "composite_valuation":    "مسودة تقييم مجمع مبدئية",
}
_DISCLAIMER = (
    "هذا التقرير مبدئي وغير معتمد، ولا يُعد تقرير خبير معتمدًا أو مستندًا صالحًا "
    "للاستخدام أمام الجهات الرسمية أو القضائية أو التمويلية قبل مراجعة واعتماد "
    "خبير التقييم المختص."
)


def _get_template_name_safe(template_id: str) -> str:
    """Return Arabic template name from registry; fall back gracefully."""
    try:
        from report_template_registry import get_template_name_ar
        return get_template_name_ar(template_id, default=template_id or "غير محدد")
    except Exception:
        return template_id or "غير محدد"


# ── PDF generation ────────────────────────────────────────────────────────────

def _build_draft_pdf(req: dict, docs_meta: list) -> Path:
    """Generate a non-certified draft PDF for any source page.

    Uses Playwright/Chromium HTML-to-PDF via pdf_renderer.
    Chromium handles Arabic shaping, RTL, and bidi natively.
    Never uses FPDF for Arabic user-facing content.
    """
    import html as _html
    from jinja2 import Environment, FileSystemLoader
    from pdf_renderer import cairo_font_css, render_pdf_from_html

    def _e(v) -> str:
        return _html.escape(str(v)) if v is not None else ""

    source_page = req.get("source_page", "")

    # Parse payload_json
    payload = req.get("payload_json") or {}
    if isinstance(payload, str):
        try:
            payload = json.loads(payload)
        except Exception:
            payload = {}

    payload_items = [
        {"key": _e(str(k)), "value": _e(str(v))}
        for k, v in list(payload.items())[:15]
        if v
    ]
    doc_names = [_e(dm.get("original_filename", "")) for dm in (docs_meta or [])]

    env      = Environment(loader=FileSystemLoader(str(_TMPL_DIR)), autoescape=False)
    template = env.get_template("expert_request_receipt.html")
    html_str = template.render(
        font_css_block=cairo_font_css(),
        pdf_title=_e(_PDF_TITLES.get(source_page, "تقرير مبدئي استرشادي")),
        request_id=_e(req.get("request_id", "")),
        created_at=_e((req.get("created_at") or "")[:10]),
        source_page=_e(source_page),
        request_kind=_e(req.get("request_kind", "")),
        user_name=_e(req.get("user_name", "")),
        phone=_e(req.get("phone", "")),
        email=_e(req.get("email", "")),
        preferred_contact_method=_e(req.get("preferred_contact_method", "")),
        summary=_e(req.get("summary", "")),
        payload_items=payload_items,
        doc_names=doc_names,
        disclaimer=_e(_DISCLAIMER),
    )

    pdf_dir  = _REPORTS / req["request_id"]
    pdf_dir.mkdir(parents=True, exist_ok=True)
    out_path = pdf_dir / "draft_report.pdf"

    pdf_bytes = render_pdf_from_html(html_str)
    out_path.write_bytes(pdf_bytes)
    return out_path


# ── Simple valuation quick PDF (───────────────────────────────────────

def _build_simple_valuation_html(payload: dict) -> str:
    """Build the RTL Arabic HTML for the simple valuation draft PDF.

    Renders the Jinja2 template at templates/pdf/simple_valuation_draft.html.
    All user-provided values are html.escape()'d before injection.
    The font CSS block is trusted internal data generated by pdf_renderer.
    """
    import html as _html
    from jinja2 import Environment, FileSystemLoader

    def _e(v) -> str:
        return _html.escape(str(v)) if v is not None else ""

    # Collect and escape payload values
    prop_type   = _e(payload.get("property_type") or "—")
    area_raw    = payload.get("area")
    area_str    = _e(f"{area_raw} م²") if area_raw else "—"
    purpose     = _e(payload.get("purpose") or "القيمة السوقية")
    val_date    = _e(payload.get("valuation_date") or "—")
    condition   = _e(payload.get("condition") or "—")
    finishing   = _e(payload.get("finishing_level") or "")
    description = _e((payload.get("description") or "")[:200])

    notes_parts: list = []
    if payload.get("notes"):
        notes_parts.append(_e(str(payload["notes"])))
    if payload.get("quick_context"):
        notes_parts.append("سؤال السياق: " + _e(str(payload["quick_context"])))
    notes_str = " | ".join(notes_parts)

    geo_parts = [
        _e(payload.get("country")  or ""),
        _e(payload.get("region")   or ""),
        _e(payload.get("city")     or ""),
        _e(payload.get("district") or ""),
    ]
    geo_str = " | ".join(p for p in geo_parts if p)

    mv      = payload.get("estimated_value")
    has_mv  = bool(mv and isinstance(mv, (int, float)) and mv > 0)
    mv_str  = f"{int(mv):,} ج.م" if has_mv else ""
    low_str = (
        f"{int(payload['price_range_low']):,} ج.م"
        if has_mv and payload.get("price_range_low") else ""
    )
    high_str = (
        f"{int(payload['price_range_high']):,} ج.م"
        if has_mv and payload.get("price_range_high") else ""
    )
    cond_mul = (
        f"×{float(payload['cond_multiplier']):.2f}"
        if has_mv and payload.get("cond_multiplier") else ""
    )
    fin_mul = (
        f"×{float(payload['fin_multiplier']):.2f}"
        if has_mv and payload.get("fin_multiplier") else ""
    )

    doc_names_raw = payload.get("doc_names") or []
    doc_names = (
        [_e(str(d)[:120]) for d in doc_names_raw[:10]]
        if isinstance(doc_names_raw, list) else []
    )

    ppsm = payload.get("price_per_sqm")
    price_per_sqm_str = (
        f"{int(ppsm):,} ج.م/م²"
        if ppsm and isinstance(ppsm, (int, float)) and ppsm > 0 else ""
    )

    tmp_ref = _e("TMP-" + uuid.uuid4().hex[:6].upper())

    # ── AVM and per-method context fields ────────────────────────────────────
    def _safe_int_str(v, suffix=" ج.م"):
        try:
            return f"{int(float(str(v))):,}{suffix}" if v else ""
        except (TypeError, ValueError):
            return str(v) if v else ""

    avm_v   = payload.get("avm_value")
    has_avm = bool(avm_v and isinstance(avm_v, (int, float)) and avm_v > 0)
    avm_str = _safe_int_str(avm_v) if has_avm else ""
    avm_low_str  = _safe_int_str(payload.get("avm_low_range"))
    avm_high_str = _safe_int_str(payload.get("avm_high_range"))

    base_ppsm_raw = payload.get("base_price_per_m2")
    base_ppsm_str = _safe_int_str(base_ppsm_raw, " ج.م/م²")
    avm_confidence = _e(str(payload.get("avm_confidence_score") or ""))
    avm_quality    = _e(str(payload.get("avm_data_quality_status") or ""))
    avm_notes_str  = _e(str(payload.get("avm_notes") or ""))
    loc_factor     = _e(str(payload.get("location_factor") or ""))
    cond_factor    = _e(str(payload.get("condition_factor") or ""))
    fin_factor     = _e(str(payload.get("finishing_factor") or ""))

    sales_v   = payload.get("sales_value") or (mv if has_mv else None)
    has_sales = bool(sales_v and isinstance(sales_v, (int, float)) and sales_v > 0)
    sales_str_tbl  = _safe_int_str(sales_v) if has_sales else ""
    sales_w        = _e(str(payload.get("sales_weight") or ""))

    income_v       = payload.get("income_value")
    has_income     = bool(income_v and isinstance(income_v, (int, float)) and income_v > 0)
    income_str_tbl = _safe_int_str(income_v) if has_income else ""
    income_w       = _e(str(payload.get("income_weight") or ""))

    cost_v_raw     = payload.get("cost_value")
    has_cost       = bool(cost_v_raw and isinstance(cost_v_raw, (int, float)) and cost_v_raw > 0)
    cost_str_tbl   = _safe_int_str(cost_v_raw) if has_cost else ""
    cost_w         = _e(str(payload.get("cost_weight") or ""))

    avm_w        = _e(str(payload.get("avm_weight") or ""))
    recon_notes  = _e(str(payload.get("reconciliation_notes") or ""))

    # ── Method context (comparable matrix, income, DCF, cost) ─────────────
    method_ctx = _build_method_context(payload)

    # Render Jinja2 template
    from pdf_renderer import cairo_font_css
    env      = Environment(loader=FileSystemLoader(str(_TMPL_DIR)), autoescape=False)
    template = env.get_template("simple_valuation_draft.html")
    return template.render(
        font_css_block=cairo_font_css(),
        val_date=val_date,
        purpose=purpose,
        geo_str=geo_str,
        prop_type=prop_type,
        area_str=area_str,
        condition=condition,
        finishing=finishing,
        description=description,
        has_mv=has_mv,
        mv_str=mv_str,
        low_str=low_str,
        high_str=high_str,
        cond_mul=cond_mul,
        fin_mul=fin_mul,
        notes_str=notes_str,
        doc_names=doc_names,
        price_per_sqm_str=price_per_sqm_str,
        tmp_ref=tmp_ref,
        # AVM fields
        has_avm=has_avm,
        avm_str=avm_str,
        avm_low_str=avm_low_str,
        avm_high_str=avm_high_str,
        avm_confidence=avm_confidence,
        avm_quality=avm_quality,
        avm_notes_str=avm_notes_str,
        base_ppsm_str=base_ppsm_str,
        loc_factor=loc_factor,
        cond_factor=cond_factor,
        fin_factor=fin_factor,
        # Per-method table fields
        has_sales=has_sales,
        sales_str_tbl=sales_str_tbl,
        sales_w=sales_w,
        has_income=has_income,
        income_str_tbl=income_str_tbl,
        income_w=income_w,
        has_cost=has_cost,
        cost_str_tbl=cost_str_tbl,
        cost_w=cost_w,
        avm_w=avm_w,
        recon_notes=recon_notes,
        # Comparable matrix + income/DCF/cost calculation tables
        comparables=method_ctx["comparables"],
        avg_adjusted_price=method_ctx.get("avg_adjusted_price", ""),
        has_comparables=method_ctx.get("has_comparables", False),
        sales_from_comps=method_ctx.get("sales_from_comps", ""),
        income_monthly_rent=method_ctx.get("income_monthly_rent", ""),
        income_annual_gross=method_ctx.get("income_annual_gross", ""),
        income_vacancy_rate=method_ctx.get("income_vacancy_rate", ""),
        income_vacancy_amt=method_ctx.get("income_vacancy_amt", ""),
        income_collection_loss_pct=method_ctx.get("income_collection_loss_pct", ""),
        income_collection_loss=method_ctx.get("income_collection_loss", ""),
        income_egi=method_ctx.get("income_egi", ""),
        income_expense_rate=method_ctx.get("income_expense_rate", ""),
        income_expenses=method_ctx.get("income_expenses", ""),
        income_reserve_pct=method_ctx.get("income_reserve_pct", ""),
        income_reserve=method_ctx.get("income_reserve", ""),
        income_noi=method_ctx.get("income_noi", ""),
        income_cap_rate_pct=method_ctx.get("income_cap_rate_pct", ""),
        income_value_calc=method_ctx.get("income_value_calc", ""),
        dcf_rows=method_ctx.get("dcf_rows", []),
        dcf_pv_cashflows=method_ctx.get("dcf_pv_cashflows", ""),
        dcf_terminal_noi=method_ctx.get("dcf_terminal_noi", ""),
        dcf_terminal_value=method_ctx.get("dcf_terminal_value", ""),
        dcf_net_terminal=method_ctx.get("dcf_net_terminal", ""),
        dcf_pv_terminal=method_ctx.get("dcf_pv_terminal", ""),
        dcf_value_calc=method_ctx.get("dcf_value_calc", ""),
        dcf_discount_rate_pct=method_ctx.get("dcf_discount_rate_pct", ""),
        dcf_growth_rate_pct=method_ctx.get("dcf_growth_rate_pct", ""),
        dcf_terminal_cap_pct=method_ctx.get("dcf_terminal_cap_pct", ""),
        discount_rate_methods=method_ctx.get("discount_rate_methods", []),
        dr_average=method_ctx.get("dr_average", ""),
        dr_expert_selected=method_ctx.get("dr_expert_selected", ""),
        dr_notes=method_ctx.get("dr_notes", ""),
        terminal_cap_methods=method_ctx.get("terminal_cap_methods", []),
        tc_average=method_ctx.get("tc_average", ""),
        tc_expert_selected=method_ctx.get("tc_expert_selected", ""),
        cost_land_value=method_ctx.get("cost_land_value", ""),
        cost_replacement_per_m2=method_ctx.get("cost_replacement_per_m2", ""),
        cost_replacement_total=method_ctx.get("cost_replacement_total", ""),
        cost_physical_depr_pct=method_ctx.get("cost_physical_depr_pct", ""),
        cost_functional_depr_pct=method_ctx.get("cost_functional_depr_pct", ""),
        cost_total_depr_pct=method_ctx.get("cost_total_depr_pct", ""),
        cost_total_depr_amt=method_ctx.get("cost_total_depr_amt", ""),
        cost_depreciated_imprv=method_ctx.get("cost_depreciated_imprv", ""),
        cost_value_calc=method_ctx.get("cost_value_calc", ""),
        cost_breakdown=method_ctx.get("cost_breakdown", []),
        cost_breakdown_total=method_ctx.get("cost_breakdown_total", ""),
        land_comps=method_ctx.get("land_comps", []),
        avg_land_price=method_ctx.get("avg_land_price", ""),
        land_value_by_sales=method_ctx.get("land_value_by_sales", ""),
        extr_improved_indication=method_ctx.get("extr_improved_indication", ""),
        extr_replacement_cost_new=method_ctx.get("extr_replacement_cost_new", ""),
        extr_depreciation_pct=method_ctx.get("extr_depreciation_pct", ""),
        extr_depr_amount=method_ctx.get("extr_depr_amount", ""),
        extr_depr_imprv_value=method_ctx.get("extr_depr_imprv_value", ""),
        extr_land_value=method_ctx.get("extr_land_value", ""),
        extr_land_per_m2=method_ctx.get("extr_land_per_m2", ""),
        extr_land_share_value=method_ctx.get("extr_land_share_value", ""),
        land_value_reconciled=method_ctx.get("land_value_reconciled", ""),
        land_value_expert_selected=method_ctx.get("land_value_expert_selected", ""),
        map_placeholder_text=method_ctx.get("map_placeholder_text", ""),
        aerial_placeholder_text=method_ctx.get("aerial_placeholder_text", ""),
        comps_map_placeholder_text=method_ctx.get("comps_map_placeholder_text", ""),
        subject_map_image_available=method_ctx.get("subject_map_image_available", False),
        subject_aerial_image_available=method_ctx.get("subject_aerial_image_available", False),
        comparables_map_image_available=method_ctx.get("comparables_map_image_available", False),
        avm_regression=method_ctx.get("avm_regression", []),
        avm_reg_base_value=method_ctx.get("avm_reg_base_value", ""),
        avm_reg_predicted=method_ctx.get("avm_reg_predicted", ""),
        avm_reg_residual=method_ctx.get("avm_reg_residual", ""),
        avm_reg_final=method_ctx.get("avm_reg_final", ""),
        avm_reg_confidence_band=method_ctx.get("avm_reg_confidence_band", ""),
        avm_reg_limitations=method_ctx.get("avm_reg_limitations", ""),
        # New data-binding fields
        price_source_data=method_ctx.get("price_source_data", []),
        mass_appraisal_bridge=method_ctx.get("mass_appraisal_bridge", {}),
        cap_rate_derivation=method_ctx.get("cap_rate_derivation", {}),
        cap_rate_methods=method_ctx.get("cap_rate_derivation", {}).get("methods", []),
        cap_rate_average=method_ctx.get("cap_rate_derivation", {}).get("average_cap_rate", ""),
        cap_rate_expert_selected=method_ctx.get("cap_rate_derivation", {}).get("expert_selected_cap_rate", ""),
        cap_rate_notes=method_ctx.get("cap_rate_derivation", {}).get("final_cap_rate_notes", ""),
        cap_rate_disclaimer=method_ctx.get("cap_rate_derivation", {}).get("disclaimer", ""),
        # Purpose / date-basis / rental
        purpose_info=method_ctx.get("purpose_info", {}),
        date_basis_info=method_ctx.get("date_basis_info", {}),
        is_rental_purpose=method_ctx.get("is_rental_purpose", False),
        rental_value_context=method_ctx.get("rental_value_context", {}),
        rental_comparables=method_ctx.get("rental_value_context", {}).get("rental_comparables", []),
    )


def _build_simple_valuation_pdf_bytes(payload: dict) -> bytes:
    """Build a non-certified advisory draft PDF using Playwright/Chromium.

    Delegates rendering to pdf_renderer.render_pdf_from_html().
    Chromium handles Arabic shaping and RTL natively.
    Never falls back to FPDF for Arabic text.
    """
    from pdf_renderer import render_pdf_from_html
    return render_pdf_from_html(_build_simple_valuation_html(payload))


# ── Certified report PDF generation ──────────────────────────────────────────

def _build_certified_report_pdf(req: dict) -> Path:
    """Generate a certified valuation report PDF using Playwright/Chromium HTML renderer.

    Only callable when approval_status == 'approved_pending_report'.
    Uses Jinja2 template at templates/pdf/certified_valuation_report.html.
    Saves to: core_engine/instance/certified_reports/<REQ-ID>/certified_report_<REQ-ID>.pdf
    Never falls back to FPDF — Chromium handles Arabic shaping and RTL natively.
    """
    import html as _html
    from jinja2 import Environment, FileSystemLoader
    from pdf_renderer import cairo_font_css, render_pdf_from_html

    def _e(v) -> str:
        return _html.escape(str(v)) if v is not None else ""

    payload = req.get("payload_json") or {}
    if isinstance(payload, str):
        try:
            payload = json.loads(payload)
        except Exception:
            payload = {}

    location = " | ".join(filter(None, [
        payload.get("country", ""),
        payload.get("region", ""),
        payload.get("city", ""),
        payload.get("district", ""),
    ]))

    area_raw = payload.get("area")
    area_str = f"{area_raw} م²" if area_raw else ""

    # Method context: comparable matrix, income, DCF, cost
    mctx = _build_method_context(payload)

    env      = Environment(loader=FileSystemLoader(str(_TMPL_DIR)), autoescape=False)
    template = env.get_template("certified_valuation_report.html")
    html_str = template.render(
        font_css_block=cairo_font_css(),
        request_id=_e(req.get("request_id", "")),
        report_template_id=req.get("report_template_id") or "",
        created_at=_e((req.get("created_at") or "")[:10]),
        report_date=_e(datetime.utcnow().strftime("%Y-%m-%d")),
        valuation_date=_e(payload.get("valuation_date", "")),
        client_name=_e(req.get("user_name", "")),
        phone=_e(req.get("phone", "")),
        email=_e(req.get("email", "")),
        preferred_contact=_e(req.get("preferred_contact_method", "")),
        report_template_name_ar=_e(_get_template_name_safe(req.get("report_template_id") or "")),
        property_type=_e(payload.get("property_type", "")),
        location=_e(location),
        area=_e(area_str),
        description=_e((payload.get("description") or "")[:300]),
        condition=_e(payload.get("condition", "")),
        finishing=_e(payload.get("finishing_level", "")),
        utilities=_e(payload.get("utilities", "")),
        ownership_type=_e(payload.get("ownership_type", "")),
        current_use=_e(payload.get("current_use", "")),
        notes=_e(payload.get("notes", "")),
        purpose=_e(payload.get("purpose") or "القيمة السوقية"),
        summary=_e(req.get("summary", "")),
        expert_recommended_value=_e(req.get("expert_recommended_value", "")),
        valuation_method_summary=_e(req.get("valuation_method_summary", "")),
        reconciliation_notes=_e(req.get("reconciliation_notes", "")),
        expert_notes=_e(req.get("expert_notes", "")),
        decision_reason=_e(req.get("decision_reason", "")),
        requested_documents=_e(req.get("requested_documents", "")),
        review_updated_at=_e((req.get("review_updated_at") or "")[:10]),
        # Per-method values from expert review fields
        sales_comparison_value=_e(req.get("sales_comparison_value", "")),
        sales_comparison_weight=_e(req.get("sales_comparison_weight", "")),
        weighted_sales=_e(req.get("weighted_sales", "")),
        income_value=_e(req.get("income_value", "")),
        income_weight=_e(req.get("income_weight", "")),
        weighted_income=_e(req.get("weighted_income", "")),
        cap_rate=_e(req.get("cap_rate", "")),
        noi=_e(req.get("noi", "")),
        cost_value=_e(req.get("cost_value", "")),
        cost_weight=_e(req.get("cost_weight", "")),
        weighted_cost=_e(req.get("weighted_cost", "")),
        land_value=_e(req.get("land_value", "")),
        replacement_cost=_e(req.get("replacement_cost", "")),
        total_depreciation=_e(req.get("total_depreciation", "")),
        dcf_value=_e(req.get("dcf_value", "")),
        dcf_weight=_e(req.get("dcf_weight", "")),
        weighted_dcf=_e(req.get("weighted_dcf", "")),
        discount_rate=_e(req.get("discount_rate", "")),
        dcf_period=_e(req.get("dcf_period", "")),
        sensitivity_low=_e(req.get("sensitivity_low", "")),
        sensitivity_high=_e(req.get("sensitivity_high", "")),
        expert_name=_e(req.get("expert_name", "")),
        expert_reg_number=_e(req.get("expert_reg_number", "")),
        # AVM context fields (from payload or expert review)
        avm_value=_e(str(payload.get("avm_value") or req.get("avm_value") or "")),
        avm_low_range=_e(str(payload.get("avm_low_range") or req.get("avm_low_range") or "")),
        avm_high_range=_e(str(payload.get("avm_high_range") or req.get("avm_high_range") or "")),
        avm_confidence_score=_e(str(payload.get("avm_confidence_score") or req.get("avm_confidence_score") or "")),
        avm_data_quality_status=_e(str(payload.get("avm_data_quality_status") or req.get("avm_data_quality_status") or "")),
        avm_notes=_e(str(payload.get("avm_notes") or req.get("avm_notes") or "")),
        base_price_per_m2=_e(str(payload.get("base_price_per_m2") or "")),
        location_factor=_e(str(payload.get("location_factor") or "")),
        condition_factor=_e(str(payload.get("condition_factor") or "")),
        finishing_factor=_e(str(payload.get("finishing_factor") or "")),
        expert_override_value=_e(str(req.get("expert_override_value") or "")),
        expert_override_reason=_e(str(req.get("expert_override_reason") or "")),
        avm_weight=_e(str(payload.get("avm_weight") or req.get("avm_weight") or "")),
        weighted_avm=_e(str(req.get("weighted_avm") or "")),
        # Comparable matrix + income/DCF/cost calculation tables
        comparables=mctx["comparables"],
        avg_adjusted_price=mctx.get("avg_adjusted_price", ""),
        has_comparables=mctx.get("has_comparables", False),
        sales_from_comps=mctx.get("sales_from_comps", ""),
        income_monthly_rent=mctx.get("income_monthly_rent", ""),
        income_annual_gross=mctx.get("income_annual_gross", ""),
        income_vacancy_rate=mctx.get("income_vacancy_rate", ""),
        income_vacancy_amt=mctx.get("income_vacancy_amt", ""),
        income_egi=mctx.get("income_egi", ""),
        income_expense_rate=mctx.get("income_expense_rate", ""),
        income_expenses=mctx.get("income_expenses", ""),
        income_noi=mctx.get("income_noi", ""),
        income_cap_rate_pct=mctx.get("income_cap_rate_pct", ""),
        income_value_calc=mctx.get("income_value_calc", ""),
        dcf_rows=mctx.get("dcf_rows", []),
        dcf_pv_cashflows=mctx.get("dcf_pv_cashflows", ""),
        dcf_terminal_value=mctx.get("dcf_terminal_value", ""),
        dcf_pv_terminal=mctx.get("dcf_pv_terminal", ""),
        dcf_value_calc=mctx.get("dcf_value_calc", ""),
        dcf_discount_rate_pct=mctx.get("dcf_discount_rate_pct", ""),
        dcf_growth_rate_pct=mctx.get("dcf_growth_rate_pct", ""),
        dcf_terminal_cap_pct=mctx.get("dcf_terminal_cap_pct", ""),
        cost_land_value=mctx.get("cost_land_value", ""),
        cost_replacement_per_m2=mctx.get("cost_replacement_per_m2", ""),
        cost_replacement_total=mctx.get("cost_replacement_total", ""),
        cost_physical_depr_pct=mctx.get("cost_physical_depr_pct", ""),
        cost_functional_depr_pct=mctx.get("cost_functional_depr_pct", ""),
        cost_total_depr_pct=mctx.get("cost_total_depr_pct", ""),
        cost_total_depr_amt=mctx.get("cost_total_depr_amt", ""),
        cost_depreciated_imprv=mctx.get("cost_depreciated_imprv", ""),
        cost_value_calc=mctx.get("cost_value_calc", ""),
        cost_breakdown=mctx.get("cost_breakdown", []),
        cost_breakdown_total=mctx.get("cost_breakdown_total", ""),
        land_comps=mctx.get("land_comps", []),
        avg_land_price=mctx.get("avg_land_price", ""),
        land_value_by_sales=mctx.get("land_value_by_sales", ""),
        extr_improved_indication=mctx.get("extr_improved_indication", ""),
        extr_replacement_cost_new=mctx.get("extr_replacement_cost_new", ""),
        extr_depreciation_pct=mctx.get("extr_depreciation_pct", ""),
        extr_depr_amount=mctx.get("extr_depr_amount", ""),
        extr_depr_imprv_value=mctx.get("extr_depr_imprv_value", ""),
        extr_land_value=mctx.get("extr_land_value", ""),
        extr_land_per_m2=mctx.get("extr_land_per_m2", ""),
        extr_land_share_value=mctx.get("extr_land_share_value", ""),
        land_value_reconciled=mctx.get("land_value_reconciled", ""),
        land_value_expert_selected=mctx.get("land_value_expert_selected", ""),
        map_placeholder_text=mctx.get("map_placeholder_text", ""),
        aerial_placeholder_text=mctx.get("aerial_placeholder_text", ""),
        comps_map_placeholder_text=mctx.get("comps_map_placeholder_text", ""),
        subject_map_image_available=mctx.get("subject_map_image_available", False),
        subject_aerial_image_available=mctx.get("subject_aerial_image_available", False),
        comparables_map_image_available=mctx.get("comparables_map_image_available", False),
        discount_rate_methods=mctx.get("discount_rate_methods", []),
        dr_average=mctx.get("dr_average", ""),
        dr_expert_selected=mctx.get("dr_expert_selected", ""),
        dr_notes=mctx.get("dr_notes", ""),
        terminal_cap_methods=mctx.get("terminal_cap_methods", []),
        tc_average=mctx.get("tc_average", ""),
        tc_expert_selected=mctx.get("tc_expert_selected", ""),
        tc_notes=mctx.get("tc_notes", ""),
        dcf_terminal_noi=mctx.get("dcf_terminal_noi", ""),
        dcf_selling_costs_pct=mctx.get("dcf_selling_costs_pct", ""),
        dcf_net_terminal=mctx.get("dcf_net_terminal", ""),
        income_collection_loss_pct=mctx.get("income_collection_loss_pct", ""),
        income_collection_loss=mctx.get("income_collection_loss", ""),
        income_reserve_pct=mctx.get("income_reserve_pct", ""),
        income_reserve=mctx.get("income_reserve", ""),
        avm_regression=mctx.get("avm_regression", []),
        avm_reg_base_value=mctx.get("avm_reg_base_value", ""),
        avm_reg_predicted=mctx.get("avm_reg_predicted", ""),
        avm_reg_residual=mctx.get("avm_reg_residual", ""),
        avm_reg_final=mctx.get("avm_reg_final", ""),
        avm_reg_confidence_band=mctx.get("avm_reg_confidence_band", ""),
        avm_reg_limitations=mctx.get("avm_reg_limitations", ""),
        # New data-binding fields
        price_source_data=mctx.get("price_source_data", []),
        mass_appraisal_bridge=mctx.get("mass_appraisal_bridge", {}),
        cap_rate_derivation=mctx.get("cap_rate_derivation", {}),
        cap_rate_methods=mctx.get("cap_rate_derivation", {}).get("methods", []),
        cap_rate_average=mctx.get("cap_rate_derivation", {}).get("average_cap_rate", ""),
        cap_rate_expert_selected=mctx.get("cap_rate_derivation", {}).get("expert_selected_cap_rate", ""),
        cap_rate_notes=mctx.get("cap_rate_derivation", {}).get("final_cap_rate_notes", ""),
        cap_rate_disclaimer=mctx.get("cap_rate_derivation", {}).get("disclaimer", ""),
        # Purpose / date-basis / rental
        purpose_info=mctx.get("purpose_info", {}),
        date_basis_info=mctx.get("date_basis_info", {}),
        is_rental_purpose=mctx.get("is_rental_purpose", False),
        rental_value_context=mctx.get("rental_value_context", {}),
        rental_comparables=mctx.get("rental_value_context", {}).get("rental_comparables", []),
    )

    pdf_dir  = _CERTIFIED_REPORTS / req["request_id"]
    pdf_dir.mkdir(parents=True, exist_ok=True)
    out_path = pdf_dir / f"certified_report_{req['request_id']}.pdf"

    pdf_bytes = render_pdf_from_html(html_str)
    out_path.write_bytes(pdf_bytes)
    return out_path

