# -*- coding: utf-8 -*-
"""
tax_appeal_extraction_templates.py — Extraction Template Catalogue for Tax Appeal Evidence.

Public API:
    _get_extraction_template_catalogue() -> list[dict]
    _get_template_for_evidence_type(evidence_type: str) -> dict | None
    EXTRACTION_TEMPLATES_BY_ID: dict[str, dict]

Rules:
    - No OCR, no Qdrant, no RAG, no internet search, no automatic extraction.
    - extraction_mode = human_manual_only for all active templates.
    - future_ocr_ready and future_qdrant_ready are metadata flags only.
    - active_now = False for all OCR/Qdrant-related capabilities.
    - All field values are manually entered by the expert.
"""
from __future__ import annotations

# ── Extraction mode constants ─────────────────────────────────────────────────

MODE_HUMAN  = "human_manual_only"
MODE_OCR    = "future_ocr_placeholder"       # inactive
MODE_QDRANT = "future_qdrant_placeholder"    # inactive

# ── Template catalogue ────────────────────────────────────────────────────────


def _field(
    field_key: str,
    label_ar: str,
    value_type: str,
    *,
    required: bool = False,
    mapped_field_key: str = "",
    help_text: str = "",
    validation_hint: str = "",
    allowed_evidence_types: list[str] | None = None,
    expert_confirmation_required: bool = True,
) -> dict:
    return {
        "field_key":                   field_key,
        "label_ar":                    label_ar,
        "value_type":                  value_type,
        "required":                    required,
        "mapped_field_key":            mapped_field_key or field_key,
        "help_text":                   help_text,
        "validation_hint":             validation_hint,
        "allowed_evidence_types":      allowed_evidence_types or [],
        "expert_confirmation_required": expert_confirmation_required,
    }


_CATALOGUE: list[dict] = [
    # ── 1. tax_notice_form3 ───────────────────────────────────────────────────
    {
        "template_id":              "tmpl_tax_notice_form3",
        "evidence_type":            "tax_notice_form3",
        "template_label_ar":        "إشعار الضريبة العقارية — نموذج 3",
        "extraction_mode":          MODE_HUMAN,
        "production_ready":         False,
        "future_ocr_ready":         True,
        "future_qdrant_ready":      False,
        "requires_human_entry":     True,
        "active_now":               True,
        "ocr_active_now":           False,
        "qdrant_active_now":        False,
        "fields": [
            _field("tax_notice_number",             "رقم الإشعار الضريبي",
                   "text",     required=True,
                   help_text="الرقم الفريد المطبوع على إشعار نموذج 3"),
            _field("notice_issue_date",             "تاريخ إصدار الإشعار",
                   "date",     required=True,
                   validation_hint="YYYY-MM-DD",
                   help_text="تاريخ صدور الإشعار من مصلحة الضرائب"),
            _field("notice_received_date",          "تاريخ استلام الإشعار",
                   "date",     required=True,
                   validation_hint="YYYY-MM-DD",
                   help_text="تاريخ استلام العميل للإشعار — يبدأ منه ميعاد الطعن 60 يومًا"),
            _field("tax_assessment_basis_date",     "تاريخ أساس التقدير الضريبي",
                   "date",     required=True,
                   validation_hint="YYYY-MM-DD",
                   help_text="تاريخ آخر حصر ضريبي — يحدد القيمة الإيجارية الحكومية"),
            _field("tax_cycle_year",                "سنة الدورة الضريبية",
                   "number",   required=False,
                   help_text="السنة الضريبية محل الطعن",
                   validation_hint="مثال: 2023"),
            _field("government_tax_amount",         "مبلغ الضريبة الحكومي",
                   "money",    required=True,
                   help_text="المبلغ الضريبي المُقدَّر من الحكومة قبل الطعن"),
            _field("government_annual_rental_value","القيمة الإيجارية السنوية الحكومية",
                   "money",    required=False,
                   help_text="القيمة الإيجارية السنوية وفق التقدير الحكومي"),
            _field("government_assessed_value",     "القيمة المُقدَّرة حكوميًا",
                   "money",    required=False,
                   help_text="القيمة السوقية أو الإيجارية وفق التقدير الحكومي"),
            _field("tax_authority_office",          "مكتب مصلحة الضرائب",
                   "text",     required=False,
                   expert_confirmation_required=False,
                   help_text="اسم المكتب الصادر منه الإشعار"),
            _field("property_tax_account_number",   "رقم الحساب الضريبي للعقار",
                   "text",     required=False,
                   help_text="رقم الملف الضريبي لدى مصلحة الضرائب العقارية"),
        ],
    },

    # ── 2. ownership_document ─────────────────────────────────────────────────
    {
        "template_id":              "tmpl_ownership_document",
        "evidence_type":            "ownership_document",
        "template_label_ar":        "وثيقة الملكية",
        "extraction_mode":          MODE_HUMAN,
        "production_ready":         False,
        "future_ocr_ready":         True,
        "future_qdrant_ready":      False,
        "requires_human_entry":     True,
        "active_now":               True,
        "ocr_active_now":           False,
        "qdrant_active_now":        False,
        "fields": [
            _field("owner_name",                    "اسم المالك",
                   "text",     required=True,
                   help_text="الاسم الكامل كما يظهر في وثيقة الملكية"),
            _field("taxpayer_name",                 "اسم الممول",
                   "text",     required=False,
                   expert_confirmation_required=False),
            _field("property_address",              "عنوان العقار",
                   "text",     required=True,
                   help_text="العنوان الكامل كما هو مثبت في الوثيقة"),
            _field("property_area",                 "مساحة العقار (م²)",
                   "number",   required=True,
                   validation_hint="أدخل رقمًا موجبًا",
                   help_text="المساحة الإجمالية كما وردت في الوثيقة"),
            _field("land_area",                     "مساحة الأرض (م²)",
                   "number",   required=False,
                   validation_hint="أدخل رقمًا موجبًا"),
            _field("unit_number",                   "رقم الوحدة",
                   "text",     required=False,
                   expert_confirmation_required=False),
            _field("building_number",               "رقم المبنى",
                   "text",     required=False,
                   expert_confirmation_required=False),
            _field("ownership_type",                "نوع الملكية",
                   "enum",     required=False,
                   validation_hint="مثال: تام، مشاع، طابقية"),
            _field("ownership_document_number",     "رقم وثيقة الملكية",
                   "text",     required=True,
                   help_text="الرقم الرسمي للوثيقة"),
            _field("ownership_date",                "تاريخ الملكية",
                   "date",     required=False,
                   validation_hint="YYYY-MM-DD"),
            _field("legal_dispute_status",          "حالة النزاع القانوني",
                   "text",     required=False,
                   help_text="ذكر أي نزاع أو رهن مُسجَّل"),
        ],
    },

    # ── 3. lease_contract ─────────────────────────────────────────────────────
    {
        "template_id":              "tmpl_lease_contract",
        "evidence_type":            "lease_contract",
        "template_label_ar":        "عقد الإيجار",
        "extraction_mode":          MODE_HUMAN,
        "production_ready":         False,
        "future_ocr_ready":         True,
        "future_qdrant_ready":      False,
        "requires_human_entry":     True,
        "active_now":               True,
        "ocr_active_now":           False,
        "qdrant_active_now":        False,
        "fields": [
            _field("tenant_name",               "اسم المستأجر",
                   "text",     required=True),
            _field("lease_start_date",          "تاريخ بداية العقد",
                   "date",     required=True,
                   validation_hint="YYYY-MM-DD"),
            _field("lease_end_date",            "تاريخ انتهاء العقد",
                   "date",     required=True,
                   validation_hint="YYYY-MM-DD"),
            _field("monthly_rent",              "الإيجار الشهري (ج.م.)",
                   "money",    required=True,
                   validation_hint="أدخل رقمًا موجبًا"),
            _field("annual_rent",               "الإيجار السنوي (ج.م.)",
                   "money",    required=False,
                   help_text="يُحسب تلقائيًا إذا تُرك فارغًا (× 12)"),
            _field("leased_area",               "المساحة المؤجَّرة (م²)",
                   "number",   required=False,
                   validation_hint="أدخل رقمًا موجبًا"),
            _field("use_type",                  "نوع الاستخدام",
                   "text",     required=False,
                   help_text="سكني، تجاري، إداري، صناعي..."),
            _field("rent_escalation_clause",    "بند الزيادة السنوية",
                   "text",     required=False,
                   help_text="نسبة الزيادة إن وجدت"),
        ],
    },

    # ── 4. activity_license ───────────────────────────────────────────────────
    {
        "template_id":              "tmpl_activity_license",
        "evidence_type":            "activity_license",
        "template_label_ar":        "ترخيص النشاط التجاري",
        "extraction_mode":          MODE_HUMAN,
        "production_ready":         False,
        "future_ocr_ready":         False,
        "future_qdrant_ready":      False,
        "requires_human_entry":     True,
        "active_now":               True,
        "ocr_active_now":           False,
        "qdrant_active_now":        False,
        "fields": [
            _field("licensed_use",              "الاستخدام المرخَّص",
                   "text",     required=True),
            _field("activity_type",             "نوع النشاط",
                   "text",     required=True),
            _field("activity_license_number",   "رقم ترخيص النشاط",
                   "text",     required=True),
            _field("activity_license_date",     "تاريخ الترخيص",
                   "date",     required=True,
                   validation_hint="YYYY-MM-DD"),
            _field("issuer",                    "الجهة المُصدِرة",
                   "text",     required=False,
                   expert_confirmation_required=False),
            _field("expiry_date",               "تاريخ انتهاء الترخيص",
                   "date",     required=False,
                   validation_hint="YYYY-MM-DD"),
        ],
    },

    # ── 5. industrial_license ─────────────────────────────────────────────────
    {
        "template_id":              "tmpl_industrial_license",
        "evidence_type":            "industrial_license",
        "template_label_ar":        "الترخيص الصناعي",
        "extraction_mode":          MODE_HUMAN,
        "production_ready":         False,
        "future_ocr_ready":         False,
        "future_qdrant_ready":      False,
        "requires_human_entry":     True,
        "active_now":               True,
        "ocr_active_now":           False,
        "qdrant_active_now":        False,
        "fields": [
            _field("industrial_license_number", "رقم الترخيص الصناعي",
                   "text",     required=True),
            _field("factory_activity",          "نشاط المصنع",
                   "text",     required=True),
            _field("issuer",                    "الجهة المُصدِرة",
                   "text",     required=False,
                   expert_confirmation_required=False),
            _field("issue_date",                "تاريخ الإصدار",
                   "date",     required=True,
                   validation_hint="YYYY-MM-DD"),
            _field("expiry_date",               "تاريخ الانتهاء",
                   "date",     required=False,
                   validation_hint="YYYY-MM-DD"),
            _field("industrial_zone",           "المنطقة الصناعية",
                   "text",     required=False),
            _field("licensed_area",             "المساحة المرخَّصة (م²)",
                   "number",   required=False,
                   validation_hint="أدخل رقمًا موجبًا"),
        ],
    },

    # ── 6. land_allocation_document ───────────────────────────────────────────
    {
        "template_id":              "tmpl_land_allocation_document",
        "evidence_type":            "land_allocation_document",
        "template_label_ar":        "وثيقة تخصيص الأرض",
        "extraction_mode":          MODE_HUMAN,
        "production_ready":         False,
        "future_ocr_ready":         False,
        "future_qdrant_ready":      False,
        "requires_human_entry":     True,
        "active_now":               True,
        "ocr_active_now":           False,
        "qdrant_active_now":        False,
        "fields": [
            _field("land_allocation_number",    "رقم التخصيص",
                   "text",     required=True),
            _field("land_area",                 "مساحة الأرض (م²)",
                   "number",   required=True,
                   validation_hint="أدخل رقمًا موجبًا"),
            _field("land_price_per_m2",         "سعر المتر المربع (ج.م.)",
                   "money",    required=False),
            _field("allocation_date",           "تاريخ التخصيص",
                   "date",     required=True,
                   validation_hint="YYYY-MM-DD"),
            _field("issuing_authority",         "جهة التخصيص",
                   "text",     required=False,
                   expert_confirmation_required=False),
            _field("industrial_zone",           "المنطقة الصناعية",
                   "text",     required=False),
            _field("usage_restrictions",        "قيود الاستخدام",
                   "text",     required=False,
                   help_text="أي قيود أو اشتراطات مذكورة في الوثيقة"),
        ],
    },

    # ── 7. area_statement ─────────────────────────────────────────────────────
    {
        "template_id":              "tmpl_area_statement",
        "evidence_type":            "area_statement",
        "template_label_ar":        "بيان المساحة",
        "extraction_mode":          MODE_HUMAN,
        "production_ready":         False,
        "future_ocr_ready":         False,
        "future_qdrant_ready":      False,
        "requires_human_entry":     True,
        "active_now":               True,
        "ocr_active_now":           False,
        "qdrant_active_now":        False,
        "fields": [
            _field("building_area",             "مساحة المبنى (م²)",
                   "number",   required=False,
                   validation_hint="أدخل رقمًا موجبًا"),
            _field("land_area",                 "مساحة الأرض (م²)",
                   "number",   required=False,
                   validation_hint="أدخل رقمًا موجبًا"),
            _field("unit_area",                 "مساحة الوحدة (م²)",
                   "number",   required=False),
            _field("floor_area",                "مساحة الطابق (م²)",
                   "number",   required=False),
            _field("measured_area",             "المساحة المقاسة الفعلية (م²)",
                   "number",   required=True,
                   validation_hint="أدخل رقمًا موجبًا",
                   help_text="المساحة الموثقة في البيان"),
            _field("measurement_source",        "مصدر القياس",
                   "text",     required=False,
                   help_text="جهة إصدار البيان"),
            _field("measurement_date",          "تاريخ القياس",
                   "date",     required=False,
                   validation_hint="YYYY-MM-DD"),
        ],
    },

    # ── 8. market_comparables_excel ───────────────────────────────────────────
    {
        "template_id":              "tmpl_market_comparables_excel",
        "evidence_type":            "market_comparables_excel",
        "template_label_ar":        "مقارنات السوق (Excel)",
        "extraction_mode":          MODE_HUMAN,
        "production_ready":         False,
        "future_ocr_ready":         False,
        "future_qdrant_ready":      True,
        "requires_human_entry":     True,
        "active_now":               True,
        "ocr_active_now":           False,
        "qdrant_active_now":        False,
        "fields": [
            _field("comparable_count",          "عدد المقارنات",
                   "number",   required=True,
                   validation_hint="أدخل عددًا صحيحًا موجبًا"),
            _field("district",                  "الحي / المنطقة",
                   "text",     required=True),
            _field("property_type",             "نوع العقار",
                   "text",     required=True),
            _field("average_price_per_m2",      "متوسط سعر المتر المربع (ج.م.)",
                   "money",    required=True),
            _field("min_price_per_m2",          "أدنى سعر للمتر المربع (ج.م.)",
                   "money",    required=False),
            _field("max_price_per_m2",          "أعلى سعر للمتر المربع (ج.م.)",
                   "money",    required=False),
            _field("reference_date",            "تاريخ المرجع",
                   "date",     required=True,
                   validation_hint="YYYY-MM-DD"),
            _field("source_quality_note",       "ملاحظة جودة المصدر",
                   "text",     required=False,
                   expert_confirmation_required=False),
        ],
    },

    # ── 9. rental_comparables_excel ───────────────────────────────────────────
    {
        "template_id":              "tmpl_rental_comparables_excel",
        "evidence_type":            "rental_comparables_excel",
        "template_label_ar":        "مقارنات الإيجار (Excel)",
        "extraction_mode":          MODE_HUMAN,
        "production_ready":         False,
        "future_ocr_ready":         False,
        "future_qdrant_ready":      True,
        "requires_human_entry":     True,
        "active_now":               True,
        "ocr_active_now":           False,
        "qdrant_active_now":        False,
        "fields": [
            _field("comparable_count",          "عدد المقارنات",
                   "number",   required=True,
                   validation_hint="أدخل عددًا صحيحًا موجبًا"),
            _field("district",                  "الحي / المنطقة",
                   "text",     required=True),
            _field("property_type",             "نوع العقار",
                   "text",     required=True),
            _field("average_rent_per_m2",       "متوسط الإيجار للمتر المربع (ج.م./شهر)",
                   "money",    required=True),
            _field("average_monthly_rent",      "متوسط الإيجار الشهري (ج.م.)",
                   "money",    required=False),
            _field("min_rent_per_m2",           "أدنى إيجار للمتر المربع",
                   "money",    required=False),
            _field("max_rent_per_m2",           "أعلى إيجار للمتر المربع",
                   "money",    required=False),
            _field("reference_date",            "تاريخ المرجع",
                   "date",     required=True,
                   validation_hint="YYYY-MM-DD"),
            _field("source_quality_note",       "ملاحظة جودة المصدر",
                   "text",     required=False,
                   expert_confirmation_required=False),
        ],
    },

    # ── 10. tax_comparables_excel ─────────────────────────────────────────────
    {
        "template_id":              "tmpl_tax_comparables_excel",
        "evidence_type":            "tax_comparables_excel",
        "template_label_ar":        "مقارنات الضريبة (Excel)",
        "extraction_mode":          MODE_HUMAN,
        "production_ready":         False,
        "future_ocr_ready":         False,
        "future_qdrant_ready":      True,
        "requires_human_entry":     True,
        "active_now":               True,
        "ocr_active_now":           False,
        "qdrant_active_now":        False,
        "fields": [
            _field("comparable_count",          "عدد المقارنات",
                   "number",   required=True,
                   validation_hint="أدخل عددًا صحيحًا موجبًا"),
            _field("district",                  "الحي / المنطقة",
                   "text",     required=True),
            _field("property_type",             "نوع العقار",
                   "text",     required=True),
            _field("average_tax_per_m2",        "متوسط الضريبة للمتر المربع (ج.م.)",
                   "money",    required=True),
            _field("min_tax_per_m2",            "أدنى ضريبة للمتر المربع",
                   "money",    required=False),
            _field("max_tax_per_m2",            "أعلى ضريبة للمتر المربع",
                   "money",    required=False),
            _field("assessment_year",           "سنة التقدير",
                   "number",   required=True,
                   validation_hint="مثال: 2023"),
            _field("source_quality_note",       "ملاحظة جودة المصدر",
                   "text",     required=False,
                   expert_confirmation_required=False),
        ],
    },

    # ── 11. factory_cost_guidance ─────────────────────────────────────────────
    {
        "template_id":              "tmpl_factory_cost_guidance",
        "evidence_type":            "factory_cost_guidance",
        "template_label_ar":        "مرشد تكلفة المصانع",
        "extraction_mode":          MODE_HUMAN,
        "production_ready":         False,
        "future_ocr_ready":         False,
        "future_qdrant_ready":      False,
        "requires_human_entry":     True,
        "active_now":               True,
        "ocr_active_now":           False,
        "qdrant_active_now":        False,
        "fields": [
            _field("production_building_cost_per_m2",
                   "تكلفة مبنى الإنتاج للمتر المربع (ج.م.)",
                   "money",    required=True),
            _field("warehouse_cost_per_m2",
                   "تكلفة المستودع للمتر المربع (ج.م.)",
                   "money",    required=False),
            _field("admin_building_cost_per_m2",
                   "تكلفة المبنى الإداري للمتر المربع (ج.م.)",
                   "money",    required=False),
            _field("external_works_cost",
                   "تكلفة الأعمال الخارجية (ج.م.)",
                   "money",    required=False),
            _field("useful_life_years",
                   "العمر الافتراضي (سنة)",
                   "number",   required=True,
                   validation_hint="أدخل عددًا صحيحًا موجبًا"),
            _field("annual_depreciation_rate",
                   "معدل الإهلاك السنوي (%)",
                   "percentage", required=True,
                   validation_hint="مثال: 0.02 لـ 2%"),
            _field("guidance_source_name",
                   "اسم مصدر المرشد",
                   "text",     required=False,
                   expert_confirmation_required=False),
            _field("guidance_date",
                   "تاريخ المرشد",
                   "date",     required=False,
                   validation_hint="YYYY-MM-DD"),
        ],
    },

    # ── 12. ain_shams_factory_cost_reference ──────────────────────────────────
    {
        "template_id":              "tmpl_ain_shams_factory_cost_reference",
        "evidence_type":            "ain_shams_factory_cost_reference",
        "template_label_ar":        "مرجع تكلفة مصانع عين شمس",
        "extraction_mode":          MODE_HUMAN,
        "production_ready":         False,
        "future_ocr_ready":         False,
        "future_qdrant_ready":      False,
        "requires_human_entry":     True,
        "active_now":               True,
        "ocr_active_now":           False,
        "qdrant_active_now":        False,
        "fields": [
            _field("reference_title",
                   "عنوان المرجع",
                   "text",     required=True),
            _field("production_building_cost_per_m2",
                   "تكلفة مبنى الإنتاج للمتر المربع (ج.م.)",
                   "money",    required=True),
            _field("warehouse_cost_per_m2",
                   "تكلفة المستودع للمتر المربع (ج.م.)",
                   "money",    required=False),
            _field("admin_building_cost_per_m2",
                   "تكلفة المبنى الإداري للمتر المربع (ج.م.)",
                   "money",    required=False),
            _field("useful_life_years",
                   "العمر الافتراضي (سنة)",
                   "number",   required=True,
                   validation_hint="أدخل عددًا صحيحًا موجبًا"),
            _field("depreciation_method",
                   "طريقة الإهلاك",
                   "text",     required=False,
                   help_text="مثال: قسط ثابت، متناقص"),
            _field("annual_depreciation_rate",
                   "معدل الإهلاك السنوي (%)",
                   "percentage", required=True,
                   validation_hint="مثال: 0.025 لـ 2.5%"),
            _field("applicability_note",
                   "ملاحظة قابلية التطبيق",
                   "text",     required=False,
                   expert_confirmation_required=False),
        ],
    },

    # ── 13. nuca_land_price_reference ─────────────────────────────────────────
    {
        "template_id":              "tmpl_nuca_land_price_reference",
        "evidence_type":            "nuca_land_price_reference",
        "template_label_ar":        "مرجع أسعار أراضي هيئة التعمير",
        "extraction_mode":          MODE_HUMAN,
        "production_ready":         False,
        "future_ocr_ready":         False,
        "future_qdrant_ready":      False,
        "requires_human_entry":     True,
        "active_now":               True,
        "ocr_active_now":           False,
        "qdrant_active_now":        False,
        "fields": [
            _field("district_or_city",
                   "المدينة / الحي",
                   "text",     required=True),
            _field("land_use",
                   "استخدام الأرض",
                   "text",     required=True,
                   help_text="مثال: صناعي، سكني، تجاري"),
            _field("land_price_per_m2",
                   "سعر الأرض للمتر المربع (ج.م.)",
                   "money",    required=True),
            _field("reference_date",
                   "تاريخ المرجع",
                   "date",     required=True,
                   validation_hint="YYYY-MM-DD"),
            _field("issuing_authority",
                   "الجهة المُصدِرة",
                   "text",     required=False,
                   expert_confirmation_required=False,
                   help_text="مثال: هيئة المجتمعات العمرانية الجديدة"),
            _field("source_note",
                   "ملاحظة المصدر",
                   "text",     required=False,
                   expert_confirmation_required=False),
        ],
    },
]

# ── Index by template_id and evidence_type ────────────────────────────────────

EXTRACTION_TEMPLATES_BY_ID: dict[str, dict] = {
    t["template_id"]: t for t in _CATALOGUE
}

_TEMPLATES_BY_EVIDENCE_TYPE: dict[str, dict] = {
    t["evidence_type"]: t for t in _CATALOGUE
}


def _get_extraction_template_catalogue() -> list[dict]:
    """Return full extraction template catalogue (no internal paths)."""
    return _CATALOGUE


def _get_template_for_evidence_type(evidence_type: str) -> dict | None:
    """Return the best matching extraction template for an evidence type, or None."""
    return _TEMPLATES_BY_EVIDENCE_TYPE.get(evidence_type)
