"""
Tests for GET /api/auth/verify — Frontend Auth #7b backend.

The frontend does not implement username/password login. Instead it accepts
a pre-existing JWT (generated by an admin via CLI or generate_token()).
GET /api/auth/verify validates the token and returns the user identity so
the frontend can display it and gate admin-only UI elements.
"""
from __future__ import annotations

import os
import sys
import time
from pathlib import Path

import pytest

_CORE = Path(__file__).resolve().parents[1]
_ROOT = _CORE.parent
for _p in (str(_CORE), str(_ROOT)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

os.chdir(str(_CORE))

from bridge_api import app  # noqa: E402
from auth.tokens import generate_token  # noqa: E402

_SECRET = "test-secret-auth-verify"
_ADMIN_ID = "alice"
_REGULAR_ID = "bob"


@pytest.fixture(autouse=True)
def env(monkeypatch):
    monkeypatch.setenv("JWT_SECRET", _SECRET)
    monkeypatch.setenv("ADMIN_USER_IDS", _ADMIN_ID)
    monkeypatch.delenv("JWT_TTL_SECONDS", raising=False)


@pytest.fixture()
def client():
    app.config["TESTING"] = True
    with app.test_client() as c:
        yield c


# ── AV01–AV03: token presence ─────────────────────────────────────────────────

class TestVerifyTokenPresence:
    def test_AV01_no_token_returns_401(self, client):
        r = client.get("/api/auth/verify")
        assert r.status_code == 401
        assert r.get_json()["status"] == "unauthorized"

    def test_AV02_invalid_token_returns_401(self, client):
        r = client.get("/api/auth/verify",
                       headers={"Authorization": "Bearer not.a.valid.token"})
        assert r.status_code == 401

    def test_AV03_valid_token_returns_200(self, client):
        token = generate_token(_ADMIN_ID)
        r = client.get("/api/auth/verify",
                       headers={"Authorization": f"Bearer {token}"})
        assert r.status_code == 200
        body = r.get_json()
        assert body["status"] == "ok"
        assert body["user_id"] == _ADMIN_ID


# ── AV04–AV06: identity fields ────────────────────────────────────────────────

class TestVerifyIdentityFields:
    def test_AV04_admin_user_returns_is_admin_true(self, client):
        token = generate_token(_ADMIN_ID)
        r = client.get("/api/auth/verify",
                       headers={"Authorization": f"Bearer {token}"})
        assert r.get_json()["is_admin"] is True

    def test_AV05_non_admin_user_returns_is_admin_false(self, client):
        token = generate_token(_REGULAR_ID)
        r = client.get("/api/auth/verify",
                       headers={"Authorization": f"Bearer {token}"})
        body = r.get_json()
        assert body["status"] == "ok"
        assert body["user_id"] == _REGULAR_ID
        assert body["is_admin"] is False

    def test_AV06_user_id_in_response_matches_token_sub(self, client):
        token = generate_token("operator-007")
        r = client.get("/api/auth/verify",
                       headers={"Authorization": f"Bearer {token}"})
        assert r.get_json()["user_id"] == "operator-007"


# ── AV07–AV08: token lifecycle ────────────────────────────────────────────────

class TestVerifyTokenLifecycle:
    def test_AV07_expired_token_returns_401(self, client):
        token = generate_token(_ADMIN_ID, ttl_seconds=1)
        time.sleep(2)
        r = client.get("/api/auth/verify",
                       headers={"Authorization": f"Bearer {token}"})
        assert r.status_code == 401

    def test_AV08_tampered_token_returns_401(self, client):
        token = generate_token(_ADMIN_ID)
        tampered = token[:-4] + "XXXX"
        r = client.get("/api/auth/verify",
                       headers={"Authorization": f"Bearer {tampered}"})
        assert r.status_code == 401


# ── AV09: HTTP method ─────────────────────────────────────────────────────────

class TestVerifyMethod:
    def test_AV09_post_to_verify_returns_405(self, client):
        r = client.post("/api/auth/verify",
                        json={"user_id": _ADMIN_ID})
        assert r.status_code == 405


# ── AV10: audit logging ───────────────────────────────────────────────────────

class TestVerifyAuditLogging:
    def test_AV10_verify_call_is_audited(self, client, tmp_path, monkeypatch):
        monkeypatch.setenv("AUDIT_ENABLED", "true")
        monkeypatch.setenv("AUDIT_DB_PATH", str(tmp_path / "audit.db"))
        monkeypatch.setenv("REPORTS_DB_PATH", str(tmp_path / "reports.db"))
        token = generate_token(_ADMIN_ID)
        client.get("/api/auth/verify",
                   headers={"Authorization": f"Bearer {token}"})
        import sqlite3
        conn = sqlite3.connect(str(tmp_path / "audit.db"))
        tables = [r[0] for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table'"
        )]
        audit_tables = [t for t in tables
                        if any(k in t.lower() for k in ("audit", "log", "access"))]
        if audit_tables:
            count = conn.execute(
                f"SELECT COUNT(*) FROM {audit_tables[0]} WHERE endpoint LIKE '/api/auth%'"
            ).fetchone()[0]
            assert count >= 1
        conn.close()
